-- 0002 auth
-- Better Auth's tables (lib/auth/server.ts maps every model and field to these
-- names): users, sessions, OAuth accounts, verification tokens (magic links),
-- organizations (= workspaces), members, invitations and the auth rate limiter.
--
-- These are NOT tenant tables: Better Auth reads them across organizations to
-- resolve sessions and memberships, so they have no row-level security. The
-- app role gets plain DML through the default privileges set up by
-- deploy/postgres/10-seo-database.sh. Tenant data lives in 0004.
--
-- Ids are uuid generated by the database (Better Auth generateId: "uuid").
-- test/integration/auth-schema.pg.test.ts compares this file with the schema
-- Better Auth expects, so a version bump that adds a field fails the suite.

CREATE TABLE auth_user (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name            text        NOT NULL,
  email           text        NOT NULL UNIQUE CHECK (email = lower(email)),
  email_verified  boolean     NOT NULL DEFAULT false,
  image           text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  -- admin plugin: 'admin' = platform admin (Lumoras staff); NULL or 'user' otherwise
  role            text        CHECK (role IS NULL OR role IN ('user', 'admin')),
  banned          boolean     DEFAULT false,
  ban_reason      text,
  ban_expires     timestamptz
);
COMMENT ON TABLE auth_user IS 'Better Auth users. role = admin marks a platform admin (Lumoras staff).';

CREATE TABLE auth_organization (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text        NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
  slug        text        NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND length(slug) <= 48),
  logo        text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  metadata    text
);
COMMENT ON TABLE auth_organization IS 'Better Auth organizations. One organization is one workspace: workspaces.id = auth_organization.id.';

CREATE TABLE auth_session (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  expires_at              timestamptz NOT NULL,
  token                   text        NOT NULL UNIQUE,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  ip_address              text,
  user_agent              text,
  user_id                 uuid        NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
  active_organization_id  uuid        REFERENCES auth_organization (id) ON DELETE SET NULL,
  -- admin plugin: set on an impersonation session to the platform admin's user id
  impersonated_by         uuid        REFERENCES auth_user (id) ON DELETE CASCADE
);
CREATE INDEX auth_session_user_id_idx ON auth_session (user_id);

CREATE TABLE auth_account (
  id                        uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id                text        NOT NULL,
  provider_id               text        NOT NULL,
  user_id                   uuid        NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
  access_token              text,
  refresh_token             text,
  id_token                  text,
  access_token_expires_at   timestamptz,
  refresh_token_expires_at  timestamptz,
  scope                     text,
  password                  text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider_id, account_id)
);
CREATE INDEX auth_account_user_id_idx ON auth_account (user_id);

CREATE TABLE auth_verification (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  identifier  text        NOT NULL,
  value       text        NOT NULL,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_verification_identifier_idx ON auth_verification (identifier);

-- Workspace roles (lib/auth/permissions.ts): owner, editor, viewer (viewer = client reviewer).
CREATE TABLE auth_member (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  uuid        NOT NULL REFERENCES auth_organization (id) ON DELETE CASCADE,
  user_id          uuid        NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
  role             text        NOT NULL DEFAULT 'viewer' CHECK (role IN ('owner', 'editor', 'viewer')),
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, user_id)
);
CREATE INDEX auth_member_user_id_idx ON auth_member (user_id);

CREATE TABLE auth_invitation (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  uuid        NOT NULL REFERENCES auth_organization (id) ON DELETE CASCADE,
  email            text        NOT NULL CHECK (email = lower(email)),
  role             text        CHECK (role IS NULL OR role IN ('owner', 'editor', 'viewer')),
  status           text        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'canceled')),
  expires_at       timestamptz NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  inviter_id       uuid        NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE
);
CREATE INDEX auth_invitation_organization_id_idx ON auth_invitation (organization_id);
CREATE INDEX auth_invitation_email_idx ON auth_invitation (email);

-- Better Auth's rate limiter (rateLimit.storage = "database"), keyed by client IP + path.
CREATE TABLE auth_rate_limit (
  id            uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  key           text    NOT NULL UNIQUE,
  count         integer NOT NULL,
  last_request  bigint  NOT NULL
);
